PLAYER_ONE = 0
PLAYER_TWO = 1
PLAYER_ONE_PITS = {0, 1, 2, 3, 4, 5}
PLAYER_TWO_PITS = {7, 8, 9, 10, 11, 12}
PLAYER_ONE_STORE = 6
PLAYER_TWO_STORE = 13

# hyperparams
HISTORY_LENGTH = 30
WAIT_TIME = 1000
FUTURE_TURNS_TO_PREDICT = 6
EXPORT_EVERY_GAMES = 1000
EXPORT_FILENAME = 'FTP_6_alpha_mancala_'
EXPORT_LOSSES_FILENAME = 'losses_'
EXPORT_FOLDER = 'models'
NUMBER_OF_TRAINING_GAMES = 10000